CREATE TABLE IF NOT EXISTS `#__ebilling_profiles` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`CondIva` int(2) NOT NULL,
	`DocTipo` int(2) NOT NULL,
	`DocNro` bigint(11) NOT NULL,
	`CondVta` int(2) NOT NULL,
	`name` varchar(255) NOT NULL DEFAULT '',
	`alias` varchar(255) NOT NULL,
	`RazonSocial` varchar(255) NOT NULL DEFAULT '',
	`type` int(1) NOT NULL DEFAULT '0',
	`Direccion` varchar(50) NOT NULL DEFAULT '',
	`address2` varchar(50) NOT NULL DEFAULT '',
	`Ciudad` varchar(50) NOT NULL DEFAULT '',
	`CodPostal` varchar(10) NOT NULL DEFAULT '',
	`Provincia` varchar(50) NOT NULL DEFAULT '',
	`Pais` varchar(50) NOT NULL DEFAULT '',
	`email` varchar(50) NOT NULL DEFAULT '',
	`phone` varchar(20) NOT NULL DEFAULT '',
	`whatsapp` varchar(20) NOT NULL DEFAULT '',
	`mobile` varchar(20) NOT NULL DEFAULT '',
	`skype` varchar(30) NOT NULL DEFAULT '',
	`web` varchar(255) NOT NULL DEFAULT '',
	`published` tinyint(1) NOT NULL DEFAULT '0',
	`ordering` int(3) NOT NULL DEFAULT '0',
	`checked_out` tinyint(1) NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime DEFAULT '0000-00-00 00:00:00',
	`created_by` int(10) NOT NULL,
	PRIMARY KEY (`id`),
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ebilling_invoices` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`CAE` varchar(20) DEFAULT NULL,
	`CAEFchVto` date DEFAULT NULL,
	`CbteNro` int(10) NOT NULL,
	`deRazonSocial` varchar(255) NOT NULL,
	`deDireccion` text NOT NULL,
	`deCondIva` varchar(255) DEFAULT NULL,
	`deDocTipo` int(3) DEFAULT NULL,
	`deDocNro` bigint(11) DEFAULT NULL,
	`deIibbNumero` varchar(12) DEFAULT NULL,
	`deInicioActividad` date DEFAULT NULL,
	`CbteTipo` varchar(20) DEFAULT NULL,
	`PtoVta` varchar(4) DEFAULT NULL,
	`CbteFch` date NOT NULL,
	`Concepto` varchar(20) DEFAULT NULL,
	`FchServDesde` date DEFAULT NULL,
	`FchServHasta` date DEFAULT NULL,
	`FchVtoPago` date NOT NULL,
	`aDocTipo` varchar(10) DEFAULT NULL,
	`aDocNum` bigint(11) DEFAULT NULL,
	`aCondIva` varchar(100) DEFAULT NULL,
	`aCondVta` varchar(100) DEFAULT NULL,
	`aRazonSocial` varchar(255) NOT NULL,
	`aDireccion` text NOT NULL,
	`aCodPostal` varchar(10) NOT NULL,
	`aCiudad` varchar(255) NOT NULL,
	`aProvincia` varchar(255) NOT NULL,
	`aPais` varchar(255) NOT NULL,
	`total` decimal(12,2) NOT NULL,
	`subtotal` decimal(12,2) NOT NULL,
	`profile_id` int(6) NOT NULL DEFAULT '0',
	`recurrent` tinyint(1) NOT NULL,
	`state` int(2) NOT NULL,
	`published` tinyint(1) NOT NULL DEFAULT '0',
	`ordering` int(3) NOT NULL DEFAULT '0',
	`checked_out` tinyint(1) NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime DEFAULT '0000-00-00 00:00:00',
	`created_by` int(10) NOT NULL,
	PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ebilling_invoice_state` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`invoice_id` int(10) NOT NULL,
	`state` int(2) NOT NULL DEFAULT '1',
	`created` datetime DEFAULT '0000-00-00 00:00:00',
	`created_by` int(10) NOT NULL,
	PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ebilling_invoices_items` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`invoice_id` int(11) NOT NULL,
	`codigo` varchar(255) NOT NULL,
	`detalle` varchar(255) NOT NULL,
	`detalle_texto` varchar(1000) NOT NULL,
	`cantidad` decimal(10,2) NOT NULL,
	`precio` decimal(12,2) NOT NULL,
	`descuentoPorcentaje` int(3) NOT NULL,
	`descuento` decimal(12,2) NOT NULL,
	`importe` decimal(10,2) NOT NULL,
	`ordering` int(11) NOT NULL,
	`product_id` int(11) NOT NULL,
	PRIMARY KEY (`id`),
	KEY `invoice_id` (`invoice_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ebilling_products` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`codigo` varchar(50) NOT NULL,
	`detalle` varchar(255) NOT NULL DEFAULT '',
	`precio` decimal(12,2) NOT NULL,
	`published` tinyint(1) NOT NULL DEFAULT '0',
	`ordering` int(3) NOT NULL DEFAULT '0',
	`checked_out` tinyint(1) NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime DEFAULT '0000-00-00 00:00:00',
	`created_by` int(10) NOT NULL,
	PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ebilling_payments` (
	`id` int(6) NOT NULL AUTO_INCREMENT,
	`invoice_id` int(11) NOT NULL,
	`codigo` varchar(50) NOT NULL,
	`detalle` varchar(255) NOT NULL DEFAULT '',
	`valor` decimal(12,2) NOT NULL,	
	`total` tinyint(1) NOT NULL DEFAULT '0',
	`published` tinyint(1) NOT NULL DEFAULT '0',
	`ordering` int(3) NOT NULL DEFAULT '0',
	`checked_out` tinyint(1) NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime DEFAULT '0000-00-00 00:00:00',
	`created_by` int(10) NOT NULL,
	PRIMARY KEY  (`id`),
	KEY `invoice_id` (`invoice_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
